### PR TITLE
chore: add basic folder structure

### PR DESCRIPTION
**Pull request by kiranwoth**
@jackwotherspoon does something like this require further explanation in a comment here? It feels self explanatory with the title, but I was wondering if I should have a couple sentences saying exactly what folders I'm adding.

Related to #3

### CODE REVIEW

**Comment by kiranwoth** [comment]
@jackwotherspoon I don't know why the test commit is in this. Is there something I need to do when changing branches?

**Comment by jackwotherspoon** [comment]
> @jackwotherspoon does something like this require further explanation in a comment here? It feels self explanatory with the title, but I was wondering if I should have a couple sentences saying exactly what folders I'm adding.
> 
> Related to #3

No doesn't really need a comment because as you mentioned it is pretty trivial and self-explanatory.

**Comment by jackwotherspoon** [comment]
> @jackwotherspoon I don't know why the test commit is in this. Is there something I need to do when changing branches?

When branching if you run `git checkout -b branch-name` it will create a branch called `branche-name` from what ever branch you are currently on. This is probably what happened here. In the future its always good to do `git checkout main` and then `git pull` prior to creating a new branch, this way your branch is up to date with main and doesnt have any stray commits from other dev branches.

**Review by jackwotherspoon — CHANGES_REQUESTED** [review]
Let's not worry about `images` and `stylesheets` folders until later. Let's start off simple and just have `docs` folder with a gitkeep, so no `static` folder or any child folders.

**Review by jackwotherspoon — CHANGES_REQUESTED** [review]
Let's not worry about `images` and `stylesheets` folders until later. Let's start off simple and just have `docs` folder with a gitkeep, so no `static` folder or any child folders.

**Comment by jackwotherspoon** [comment]
@kiranwoth friendly ping here, anything I can help with to try and keep this ball rolling?

**Comment by kiranwoth** [comment]
> @kiranwoth friendly ping here, anything I can help with to try and keep this ball rolling?

Sorry! I got my dental implants on Tuesday and it hit me harder then I thought it would. I just hadn't checked this

**Review by jackwotherspoon — APPROVED** [review]

**Comment by jackwotherspoon** [comment]
@kiranwoth Nice work! You may want to update a few repo settings to make life easier down the road.

I would suggest going to "Settings" and updating the "Pull Requests" section to look like as follows:
image

These changes help keep commit history easy to follow and cleans up merged branches by auto-deleting them 😄

**Pull request merged**
